# Generated by Django 4.1.2 on 2022-10-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='confirm_password',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='mob_no',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='password',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
