# Generated by Django 4.1.2 on 2022-10-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_input_confirm_password_alter_input_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='confirm_password',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='mob_no',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
