# Generated by Django 4.1.2 on 2022-11-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_input_confirm_password_alter_input_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='confirm_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
