# Generated by Django 4.1.2 on 2022-11-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_input_confirm_password_alter_input_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=100, unique=True),
        ),
    ]
